#!/bin/sh

# #######################################################################
# #                            AUTOSTART                                #
# #######################################################################

pgrep -x sxhkd > /dev/null || sxhkd & 		# Keybindings
$HOME/.config/polybar/launch.sh & 		# Polybar
$HOME/.fehbg & 					# feh wallpaper
nm-applet &		 			# NetworkManager
picom --experimental-backends -b & 		# Compositor
dunst & 					# Notify Daemon
$HOME/.local/bin/locker & # lock screen on sleep with i3lock-fancy

# #######################################################################
# #                           WINDOWS CONFIG                            #
# #######################################################################

#bspc rule -r "*"

bspc monitor -d I II III IV V VI

bspc config border_width           0
bspc config window_gap             20
bspc config top_padding            0
bspc config bottom_padding         0
bspc config left_padding           0
bspc config right_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# #######################################################################
# #                               RULES                                 #
# #######################################################################

bspc rule -a Zathura state=tiled
#bspc rule -a Emacs state=tiled
#bspc rule -a Thunar desktop='^6'

