#!/bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

$HOME/.fehbg

bspc monitor LVDS1  -d I II III IV V

### Windows Conf ###
bspc config border_width           0
bspc config window_gap             30 #50
bspc config top_padding            0
bspc config bottom_padding         0
bspc config left_padding           0
bspc config right_padding          0

# Layout
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# custom rule
bspc rule -a Zathura state=tiled

nm-applet &
picom --experimental-backends -b
dunst > /dev/null &
