require('mappings')
require('noornee/nvim-treesitter')
require('settings')
require('plugins')
require('colorbuddy').colorscheme('gruvbox')
require('lualine').setup()
require('nvim-autopairs').setup()
