#!/bin/sh

# #######################################################################
# #                            AUTOSTART                                #
# #######################################################################

pgrep -x sxhkd > /dev/null || sxhkd & 		# Keybindings
$HOME/.config/polybar/launch.sh & 			# Polybar
$HOME/.fehbg & 								# feh wallpaper
nm-applet &		 							# NetworkManager
picom -b									# Compositor
dunst & 									# Notify Daemon

# #######################################################################
# #                           WINDOWS CONFIG                            #
# #######################################################################

#bspc rule -r "*"

bspc monitor LVDS-1 -d I II III IV V VI
bspc monitor DP-1-3 -d VII VIII IX X

bspc config border_width           1
bspc config window_gap             20
bspc config top_padding            0
bspc config bottom_padding         0
bspc config left_padding           0
bspc config right_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# #######################################################################
# #                               RULES                                 #
# #######################################################################

bspc rule -a Zathura state=tiled
bspc rule -a Thunar desktop='^6'

